// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorCode.proto

#include "ErrorCode.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace ErrorCode {
}  // namespace ErrorCode
void InitDefaults_ErrorCode_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_ErrorCode_2eproto = nullptr;
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_ErrorCode_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_ErrorCode_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_ErrorCode_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static constexpr ::google::protobuf::Message* const* file_default_instances = NULL;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_ErrorCode_2eproto = {
  {}, AddDescriptors_ErrorCode_2eproto, "ErrorCode.proto", schemas,
  file_default_instances, TableStruct_ErrorCode_2eproto::offsets,
  file_level_metadata_ErrorCode_2eproto, 0, file_level_enum_descriptors_ErrorCode_2eproto, file_level_service_descriptors_ErrorCode_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_ErrorCode_2eproto = {
  false, InitDefaults_ErrorCode_2eproto, 
  "\n\017ErrorCode.proto\022\tErrorCode*\223\002\n\rEnumErr"
  "orCode\022\020\n\014CODE_SUCCESS\020\000\022\027\n\023CODE_PARAMET"
  "ER_NULL\020\001\022\032\n\026CODE_PARAMETER_INVALID\020\002\022\032\n"
  "\026CODE_WAIT_RESP_TIMEOUT\020\003\022\025\n\021CODE_SYSTEM"
  "_ERROR\020\004\022\026\n\022CODE_ACOCUNT_EMPTY\020\007\022\024\n\020CODE"
  "_LOGIN_ERROR\020\010\022!\n\034CODE_CHECK_GAME_TOKEN_"
  "FAILED\020\350\007\022\035\n\030CODE_SESSION_HAV_NO_USER\020\351\007"
  "\022\030\n\023CODE_INVALID_ROOMID\020\321\017b\006proto3"
,
  "ErrorCode.proto", &assign_descriptors_table_ErrorCode_2eproto, 314,
};

void AddDescriptors_ErrorCode_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_ErrorCode_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ErrorCode_2eproto = []() { AddDescriptors_ErrorCode_2eproto(); return true; }();
namespace ErrorCode {
const ::google::protobuf::EnumDescriptor* EnumErrorCode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_ErrorCode_2eproto);
  return file_level_enum_descriptors_ErrorCode_2eproto[0];
}
bool EnumErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 7:
    case 8:
    case 1000:
    case 1001:
    case 2001:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ErrorCode
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
