// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameCmd.proto

#include "GameCmd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace GameCmd {
}  // namespace GameCmd
void InitDefaults_GameCmd_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_GameCmd_2eproto = nullptr;
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_GameCmd_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_GameCmd_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_GameCmd_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static constexpr ::google::protobuf::Message* const* file_default_instances = NULL;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_GameCmd_2eproto = {
  {}, AddDescriptors_GameCmd_2eproto, "GameCmd.proto", schemas,
  file_default_instances, TableStruct_GameCmd_2eproto::offsets,
  file_level_metadata_GameCmd_2eproto, 0, file_level_enum_descriptors_GameCmd_2eproto, file_level_service_descriptors_GameCmd_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_GameCmd_2eproto = {
  false, InitDefaults_GameCmd_2eproto, 
  "\n\rGameCmd.proto\022\007GameCmd*\360\t\n\013EnumGameCmd"
  "\022\r\n\tCMD_BEGIN\020\000\022\031\n\024CMD_APPLY_ENTER_ROOM\020"
  "\350\007\022\030\n\023CMD_APPLY_QUIT_ROOM\020\351\007\022\023\n\016CMD_FLUS"
  "H_ROOM\020\352\007\022\023\n\016CMD_APPLY_SEAT\020\353\007\022\027\n\022CMD_PL"
  "AYER_SITDOWN\020\354\007\022\026\n\021CMD_APPLY_STANDUP\020\355\007\022"
  "\027\n\022CMD_PLAYER_STANDUP\020\356\007\022\030\n\023CMD_APPLY_FL"
  "USHROOM\020\357\007\022\025\n\020CMD_PLAYER_BUYIN\020\360\007\022\023\n\016CMD"
  "_DEAL_CARDS\020\362\007\022\027\n\022CMD_APPLY_FACESHOW\020\363\007\022"
  "\030\n\023CMD_PLAYER_FACESHOW\020\364\007\022\023\n\016CMD_APPLY_C"
  "HAT\020\365\007\022\024\n\017CMD_PLAYER_CHAT\020\366\007\022\030\n\023CMD_APPL"
  "Y_USE_PROPS\020\367\007\022\031\n\024CMD_PLAYER_USE_PROPS\020\370"
  "\007\022\034\n\027CMD_APPLY_PRESENT_CHIPS\020\371\007\022\035\n\030CMD_P"
  "LAYER_PRESENT_CHIPS\020\372\007\022\033\n\026CMD_APPLY_PRES"
  "ENT_GIFT\020\373\007\022\034\n\027CMD_PLAYER_PRESENT_GIFT\020\374"
  "\007\022\032\n\025CMD_PLAYER_ENTER_ROOM\020\375\007\022\031\n\024CMD_PLA"
  "YER_QUIT_ROOM\020\376\007\022\037\n\032CMD_APPLY_TRANSMIT_M"
  "ESSAGE\020\377\007\022 \n\033CMD_PLAYER_TRANSMIT_MESSAGE"
  "\020\200\010\022$\n\037CMD_APPLY_PRESENT_GIFT_NEWINTER\020\202"
  "\010\022%\n CMD_PLAYER_PRESENT_GIFT_NEWINTER\020\203\010"
  "\022\032\n\025CMD_PLAYER_TRUSTEE_ON\020\204\010\022\032\n\025CMD_APPL"
  "Y_TRUSTEE_OFF\020\205\010\022\033\n\026CMD_PLAYER_TRUSTEE_O"
  "FF\020\206\010\022\026\n\021CMD_ACTIVE_PLAYER\020\207\010\022\027\n\022CMD_APP"
  "LY_DIG_CARD\020\210\010\022\030\n\023CMD_PLAYER_DIG_CARD\020\211\010"
  "\022\023\n\016CMD_APPLY_DROP\020\212\010\022\024\n\017CMD_PLAYER_DROP"
  "\020\213\010\022\030\n\023CMD_APPLY_POST_CARD\020\214\010\022\031\n\024CMD_PLA"
  "YER_POST_CARD\020\215\010\022\026\n\021CMD_APPLY_DECLARE\020\216\010"
  "\022\027\n\022CMD_PLAYER_DECLARE\020\217\010\022\033\n\026CMD_APPLY_L"
  "OSE_DECLARE\020\220\010\022\034\n\027CMD_PLAYER_LOSE_DECLAR"
  "E\020\221\010\022\022\n\rCMD_GAME_OVER\020\222\010\022\032\n\025CMD_APPLY_RO"
  "OM_STATUS\020\223\010\022\031\n\024CMD_NOTIFY_WAIT_GAME\020\224\010\022"
  "\025\n\020CMD_SHUFFLE_CARD\020\225\010\022 \n\033CMD_APPLY_CLOS"
  "E_ACCOUNT_BOX\020\226\010\022!\n\034CMD_PLAYER_CLOSE_ACC"
  "OUNT_BOX\020\227\010"
,
  "GameCmd.proto", &assign_descriptors_table_GameCmd_2eproto, 1291,
};

void AddDescriptors_GameCmd_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_GameCmd_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_GameCmd_2eproto = []() { AddDescriptors_GameCmd_2eproto(); return true; }();
namespace GameCmd {
const ::google::protobuf::EnumDescriptor* EnumGameCmd_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_GameCmd_2eproto);
  return file_level_enum_descriptors_GameCmd_2eproto[0];
}
bool EnumGameCmd_IsValid(int value) {
  switch (value) {
    case 0:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1010:
    case 1011:
    case 1012:
    case 1013:
    case 1014:
    case 1015:
    case 1016:
    case 1017:
    case 1018:
    case 1019:
    case 1020:
    case 1021:
    case 1022:
    case 1023:
    case 1024:
    case 1026:
    case 1027:
    case 1028:
    case 1029:
    case 1030:
    case 1031:
    case 1032:
    case 1033:
    case 1034:
    case 1035:
    case 1036:
    case 1037:
    case 1038:
    case 1039:
    case 1040:
    case 1041:
    case 1042:
    case 1043:
    case 1044:
    case 1045:
    case 1046:
    case 1047:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace GameCmd
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
