// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginCmd.proto

#ifndef PROTOBUF_INCLUDED_LoginCmd_2eproto
#define PROTOBUF_INCLUDED_LoginCmd_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_LoginCmd_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_LoginCmd_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_LoginCmd_2eproto();
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
namespace LoginCmd {

enum EnumLoginCmd {
  CMD_BEGIN = 0,
  CMD_LOGIN = 1000,
  CMD_ROBOT_LOGIN = 1001,
  CMD_NOTIFY_LOGIN = 1002,
  CMD_USER_TOKEN_LOGIN = 1003,
  EnumLoginCmd_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  EnumLoginCmd_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool EnumLoginCmd_IsValid(int value);
const EnumLoginCmd EnumLoginCmd_MIN = CMD_BEGIN;
const EnumLoginCmd EnumLoginCmd_MAX = CMD_USER_TOKEN_LOGIN;
const int EnumLoginCmd_ARRAYSIZE = EnumLoginCmd_MAX + 1;

const ::google::protobuf::EnumDescriptor* EnumLoginCmd_descriptor();
inline const ::std::string& EnumLoginCmd_Name(EnumLoginCmd value) {
  return ::google::protobuf::internal::NameOfEnum(
    EnumLoginCmd_descriptor(), value);
}
inline bool EnumLoginCmd_Parse(
    const ::std::string& name, EnumLoginCmd* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumLoginCmd>(
    EnumLoginCmd_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace LoginCmd

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::LoginCmd::EnumLoginCmd> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::LoginCmd::EnumLoginCmd>() {
  return ::LoginCmd::EnumLoginCmd_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_LoginCmd_2eproto
