// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgType.proto

#ifndef PROTOBUF_INCLUDED_MsgType_2eproto
#define PROTOBUF_INCLUDED_MsgType_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MsgType_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_MsgType_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_MsgType_2eproto();
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
namespace MsgType {

enum EnumMsgType {
  FIRST_VALUE = 0,
  REQUEST_MASK = 16384,
  RESPONSE_MASK = 32768,
  NOFIFY_MASK = 5,
  SYN_REQUEST = 16385,
  SYN_RESPONSE = 32769,
  ASYN_REQUEST = 16386,
  ASYN_RESPONSE = 32770,
  REGISTER_REQUEST = 16387,
  REGISTER_RESPONSE = 32771,
  HEARTBEAT_REQUEST = 16388,
  HEARTBEAT_RESPONSE = 32772,
  NOTIFY_REQUEST = 16389,
  NOTIFY_RESPONSE = 32773,
  EnumMsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  EnumMsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool EnumMsgType_IsValid(int value);
const EnumMsgType EnumMsgType_MIN = FIRST_VALUE;
const EnumMsgType EnumMsgType_MAX = NOTIFY_RESPONSE;
const int EnumMsgType_ARRAYSIZE = EnumMsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* EnumMsgType_descriptor();
inline const ::std::string& EnumMsgType_Name(EnumMsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    EnumMsgType_descriptor(), value);
}
inline bool EnumMsgType_Parse(
    const ::std::string& name, EnumMsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumMsgType>(
    EnumMsgType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgType

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MsgType::EnumMsgType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MsgType::EnumMsgType>() {
  return ::MsgType::EnumMsgType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_MsgType_2eproto
