// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgType.proto

#include "MsgType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace MsgType {
}  // namespace MsgType
void InitDefaults_MsgType_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_MsgType_2eproto = nullptr;
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_MsgType_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_MsgType_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_MsgType_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static constexpr ::google::protobuf::Message* const* file_default_instances = NULL;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_MsgType_2eproto = {
  {}, AddDescriptors_MsgType_2eproto, "MsgType.proto", schemas,
  file_default_instances, TableStruct_MsgType_2eproto::offsets,
  file_level_metadata_MsgType_2eproto, 0, file_level_enum_descriptors_MsgType_2eproto, file_level_service_descriptors_MsgType_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_MsgType_2eproto = {
  false, InitDefaults_MsgType_2eproto, 
  "\n\rMsgType.proto\022\007MsgType*\271\002\n\013EnumMsgType"
  "\022\017\n\013FIRST_VALUE\020\000\022\022\n\014REQUEST_MASK\020\200\200\001\022\023\n"
  "\rRESPONSE_MASK\020\200\200\002\022\017\n\013NOFIFY_MASK\020\005\022\021\n\013S"
  "YN_REQUEST\020\201\200\001\022\022\n\014SYN_RESPONSE\020\201\200\002\022\022\n\014AS"
  "YN_REQUEST\020\202\200\001\022\023\n\rASYN_RESPONSE\020\202\200\002\022\026\n\020R"
  "EGISTER_REQUEST\020\203\200\001\022\027\n\021REGISTER_RESPONSE"
  "\020\203\200\002\022\027\n\021HEARTBEAT_REQUEST\020\204\200\001\022\030\n\022HEARTBE"
  "AT_RESPONSE\020\204\200\002\022\024\n\016NOTIFY_REQUEST\020\205\200\001\022\025\n"
  "\017NOTIFY_RESPONSE\020\205\200\002b\006proto3"
,
  "MsgType.proto", &assign_descriptors_table_MsgType_2eproto, 348,
};

void AddDescriptors_MsgType_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_MsgType_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_MsgType_2eproto = []() { AddDescriptors_MsgType_2eproto(); return true; }();
namespace MsgType {
const ::google::protobuf::EnumDescriptor* EnumMsgType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_MsgType_2eproto);
  return file_level_enum_descriptors_MsgType_2eproto[0];
}
bool EnumMsgType_IsValid(int value) {
  switch (value) {
    case 0:
    case 5:
    case 16384:
    case 16385:
    case 16386:
    case 16387:
    case 16388:
    case 16389:
    case 32768:
    case 32769:
    case 32770:
    case 32771:
    case 32772:
    case 32773:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace MsgType
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
